apiVersion: apps/v1
kind: Deployment
metadata:
  name: drainable-service
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: drainable-service
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          # Shows why naive preStop (just sleep) is bad: delays deletion without draining
